<?php

namespace AppBundle\Repository;

/**
 * CategoryMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryMappingRepository extends \Doctrine\ORM\EntityRepository
{
}
