<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\Criteria;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllExcludeId($id, $category, $limit) {

        $query = $this->createQueryBuilder('p')
        ->where('p.id <> :id AND p.category = :category')
        ->setParameters(array("id" => $id, "category" => $category))
        ->orderBy('p.modified', 'DESC')
        ->setMaxResults($limit)
        ->getQuery();

        return $query->getResult();

    }
}
