twig:
  globals:
    cyberlunes:
      d1:
        title: "Audífonos EXTRA BASS™ XB550AP"
        description: "Deja que la música fluya con toda la potencia de EXTRA BASS. Escoge entre cinco colores vibrantes el que mejor se adapte a tu estilo. #CYBERLUNES 13% de descuento. Precio original $149.900 COP"
        img: "img/deals/audifonos-extra-bass.jpg"
        link: "https://store.sony.com.co/mdr-xb550ap/p"
        store: "sony"
        price: "$ 129.903 COP"
      d2:
        title: "BUZO CON CAPUCHA BADGE OF SPORT"
        description: "UN BUZO CÓMODO QUE IRRADIA TU AMOR POR ADIDAS.<br>
          Pon este buzo con capucha sobre tu ropa para entrenar y ve al gimnasio. Está confeccionado en felpa gruesa de una mezcla de algodón que es suave al tacto.<br>
          #CYBERLUNES 60% de descuento. Precio original $189.900 COP"
        img: "img/deals/buzo-con-capucha-badge-of-sport-adidas.jpg"
        link: "https://www.adidas.co/buzo-con-capucha-badge-of-sport/CX4206.html"
        store: "adidas"
        price: "$ 75.960 COP"
      d3:
        title: "Audífonos inalámbricos CH500"
        description: "Escucha música todo el día sin interrupciones. Transmite de manera inalámbrica mediante conexión BLUETOOTH® con un emparejamiento sencillo gracias a la tecnología NFC™ One-Touch y una batería duradera de hasta 20 horas de autonomía. #CYBERLUNES 26% descuento. Precio original $229.900 COP"
        img: "img/deals/audifonos-inalambricos-ch500.jpg"
        link: "https://store.sony.com.co/wh-ch500/p"
        store: "sony"
        price: "$ 169.873 COP"
