#Data from each store, product or service to show in the site
twig:
  globals:
    seo:
      name: "CC Online Stores"
      title: "#QuédateEnCasa Colombia - CC Online Stores, las mejores tiendas virtuales, promociones, ofertas, descuentos y productos en un mismo lugar. BLACK FRIDAY"
      description: "#QuédateEnCasa Colombia - Centro Comercial Online Stores, encuentra todas las tiendas virtuales más importantes y con los mejores descuentos, ofertas y productos, outlets, cupones de descuento y tiendas en línea, todo en un solo lugar. BLACK FRIDAY"
      img: "img/logo.jpg"
      site: "cconlinestores.com"
      url: "https://cconlinestores.com"
      author: "kbitssd"
    seo_sections:
      stores:
        name: "Tiendas en línea, online stores y black friday en Noviembre"
        title: "#QuédateEnCasa Tiendas en línea y BLACK FRIDAY Colombia. Las mejores online stores en un mismo lugar."
        description: "#QuédateEnCasa Centro Comercial Virtual de las Tiendas en línea, acá encuentrarás todas las tiendas virtuales más importantes, outlets y online stores, todo en un solo lugar. BLACK FRIDAY Colombia."
        img:
        site: "cconlinestores.com"
        url: "https://cconlinestores.com/stores"
        author: "kbitssd"
      deals:
        name: "Ofertas en línea, promociones, descuentos y black friday en Colombia"
        title: "#QuédateEnCasa BLACK FRIDAY Colombia con las mejores ofertas y descuentos del momento, todo en un sólo lugar."
        description: "#QuédateEnCasa Encuentra todas las Ofertas y promociones más destacadas del momento en internet. En Online Stores tenemos las promociones y descuentos de las tiendas en línea más importantes del mundo, outlets y online stores. BLACK FRIDAY Colombia en Mayo y Noviembre."
        img:
        site: "cconlinestores.com"
        url: "https://cconlinestores.com/ofertas"
        author: "kbitssd"
      blackfriday:
        name: "Ofertas Black Friday 2020"
        title: "#QuédateEnCasa BLACK FRIDAY Colombia 2020 con las mejores ofertas y descuentos del momento."
        description: "#QuédateEnCasa Encuentra las mejores ofertas, descuentos y productos en BLACK FRIDAY Colombia 2020. Todos los descuentos y ofertas del próximo black friday el 17 de mayo de 2020."
        img: "img/deals/black-friday.png"
        site: "cconlinestores.com"
        url: "https://cconlinestores.com/blackfriday"
        author: "kbitssd"
      cyberlunes:
        name: "Ofertas Cyberlunes 2020"
        title: "#QuédateEnCasa CYBERLUNES Colombia 2020 con las mejores ofertas y descuentos del momento."
        description: "#QuédateEnCasa Encuentra las mejores ofertas, descuentos y productos en CYBERLUNES Colombia 2020 en Noviembre. Todos los descuentos y ofertas del próximo cyberlunes de 2020."
        img: "img/stores/logo-cyberlunes.png"
        site: "cconlinestores.com"
        url: "https://cconlinestores.com/cyberlunes"
        author: "kbitssd"