twig:
  globals:
    deals:
      d11:
        title: "Prepárate para CYBERLUNES® este 19 y 20 de noviembre de 2018."
        description: "¡Aprovecha Cyberlunes® Colombia este 19 y 20 de noviembre! Disfruta súper descuentos y precios bajos para que compres por internet tus marcas favoritas."
        img: "img/deals/cyberlunes.png"
        link: "https://www.cyberlunes.com.co/"
        store: "cyberlunes"
      d10:
        title: "¡Ya llega #Cyberlunes! en Sony"
        description: "Cyberlunes en Sony Store con descuentos hasta del 60%."
        img: "img/deals/sony-cyberlunes.png"
        link: "https://store.sony.com.co/cyberlunes"
        store: "sony"
#      d7:
#        title: "Madrugón Falabella"
#        description: "Mañana 3 de noviembre de 2018 gran Madrugón Falabella, descuentos exclusivos pagando con tus tarjetas Banco Falabella."
#        img: "img/deals/madrugon-falabella.jpg"
#        link: "http://ma.sv/MipvGT"
#        store: "falabella"
      d9:
        title: "¡Ya empezó! Vive los Black Days con Homecenter"
        description: "Balck Days Homecenter. Precios bajos para que ahorres más. Válido del 8 al 28 de noviembre de 2018."
        img: "img/deals/blackdays-homecenter.jpg"
        link: "https://www.homecenter.com.co/homecenter-co/category/cat4220001/"
        store: "homecenter"
#      d8:
#        title: "Hoy Gran Trasnochon Falabella"
#        description: "Hoy 8 de noviembre de 2018 Banco Falabella tiene para ti el gran Trasnochon Falabella de 6pm a 11pm, descuentos exclusivos pagando con tus tarjetas Banco Falabella."
#        img: "img/deals/trasnochon-falabella.jpg"
#        link: "http://ma.sv/MEfsvL"
#        store: "falabella"
#      d6:
#        title: "MEGA Precios en llantas MAXXIS"
#        description: "Descuentos en llantas MAXXIS en neumarket.com<br><p class='text-right'><em><small>promoción válida hasta el 31 de octubre</small></em></p>"
#        img: "img/deals/mega-precios-en-llantas.jpg"
#        link: "https://www.neumarket.com/mega-precios-maxxis"
#        store: "neumarket"
#      d1:
#        title: "Uber Eats 25% de descuento"
#        description: "25% de descuento en todos tus pedidos por la aplicacióncon Uber Eats usando el código <strong>SEGUIMOSCELEBRANDO</strong>, válido hasta el 31 de Octubre."
#        img: "img/stores/uber_eats.png"
#        link: "https://www.ubereats.com"
#        store: "uber eats"
      d5:
        title: "Portátil HP Intel Celeron N3060 - 14 Pulgadas"
        description: "Portátil HP - 14-AX026LA - Intel Celeron N3060 - 14 Pulgadas - Disco Duro 32GB - Gris.<br>
          Características:<br>
          - Procesador Intel Celeron N3060<br>
          - Sistema Operativo Windows 10 Home<br>
          - Memoria RAM 4GB<br>
          - Disco Duro 32GB<br>Pantalla 14 Pulgadas"
        img: "img/deals/portatil-HP-Intel-Celeron-N3060.jpg"
        link: "https://www.ktronix.com/portatil-hp-14-ax026la-intel-celeron-n3060-14-pulgadas-disco-duro-32gb-gris"
        store: "ktronix"
      d3:
        title: "Mazda 3 Hatchback"
        description: "Mazda 3 lleva Jinba-Ittai a un nivel superior con la introducción de una mejorada dinámica de manejo, a través del nuevo sistema de Control G-Vectoring (GVC). Y la serie integrada de tecnologías de seguridad i-ACTIVSENSE que incluye los más modernos sensores para mantenerlo informado de los peligros potenciales."
        img: "img/deals/mazda-3.jpg"
        link: "https://www.mazda.com.co/cars/mazda-3-hatchback/"
        store: "mazda"
      d2:
        title: "Smart TV (Android TV) 4K Ultra HD SONY"
        description: "Televisor 65 pulgadas SONY OLED 4K HDR A8F, con Dolby Vision, Acoustic Surface e índice de alto contraste, que ofrece tonos negros puros."
        img: "img/deals/bravia-oled.jpg"
        link: "https://store.sony.com.co/xbr-65a8f/p"
        store: "sony"
      d4:
        title: "Lleva tu combo Logitech G de altavoz y mouse por solo $ 699.900"
        description: "Parlantes Gamer Logitech G560 RGB y Mouse Logitech G203. Altavoz para gaming en PC Lightsync sólo en teknopolis.co"
        img: "img/deals/combo-parlantes-gamer-mouse-logitech.jpg"
        link: "https://www.teknopolis.co/parlantes-gamer-logitech-g560-rgb-mouse-logitech-g203/p"
        store: "teknopolis"